### PR TITLE
fix: changed size of svg images

### PR DESCRIPTION
**Pull request by abhinavraj23**
**Fixes:** 
#19 

**Changes made**
 Earlier the svg images were very small and thus were not clear, now the size is increased and are thus clear enough.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a screenshot to one of the pages and a test link to a website.

**Comment by harsh-2711** [comment]
Still changes are needed as all the schematics have a very small size and aren't clearly visible like : 
screenshot from 2018-06-01 22-14-08

Some of the schematics have path changed and so are missing and only a box appears
screenshot from 2018-06-01 22-14-43

Size of screenshots and schematics are different
screenshot from 2018-06-01 22-14-32

Request: Please keep height and width of the schematics(not applicable to every image) same

**Comment by abhinavraj23** [comment]
@harsh-2711 I have  kept the dimensions 500 X 200 for all the images as most of them are clearly visible and are not over-sized with these dimensions but if you want I can still make them larger

**Comment by abhinavraj23** [comment]
@harsh-2711 I have changed the dimensions to 500 X 500 now all the images are very much visible
changed_pic

**Comment by harsh-2711** [comment]
@abhinavraj23  Can you please provide link to your github page so that everyone can review and we don't need to search for changes in your repo.

**Comment by abhinavraj23** [comment]
https://github.com/abhinavraj23/pslab-experiments here its is @harsh-2711  :+1:

**Pull request merged**
