### PR TITLE
fix: Images folder moved to parent folder from experiments folder

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes: #3 #10

### CODE REVIEW

**Comment by mariobehling** [comment]
Please read the issue carefully and fix everything correctly -> according to the issue.

Also ensure that the images work on the pages in the md-file!

**Comment by harsh-2711** [comment]
I have added one commit which fixes the issue of images.
NOTE: I have used direct path instead of relative as there was no way to use relative path as markdown files don't support directly calling root folder

**Comment by mariobehling** [comment]
Please use relative path and check that the website builds. Sometimes things don't work in markdown, but these things do work in the generated website.

**Comment by harsh-2711** [comment]
@mariobehling  Relative links are only possible when the folder to be referenced is contained inside the current working folder but here the images folder is outside the folder of experiments and so relative paths don't work..

**Comment by mariobehling** [comment]
Please provide links to documentation where it is stated that this is not possible.

**Pull request merged**
